### ISSUE TITLE
GlideUtils类代码优化

### ISSUE THREAD

**Issue by hczcgq** [QiYuan007/EasyFrame#2]
可以把GlideUtilts中的图片加载代代码优化，同一种类型可以用一个方法完成
 public static void into(Context context, Object obj, ImageView view) {
        DrawableTypeRequest<String> request = Glide.with(context).load(obj);
        if (mImageId != -1) {
            request.placeholder(mImageId);
        }
        request.crossFade()//淡入淡出
                .centerCrop() // 缩放图片让图片充满整个ImageView的边框，然后裁掉超出的部分
                .into(view);

    }

**Comment by QiYuan007** [comment]
赞，倒出时间后我在对整体的代码做一个优化，非常感谢你的宝贵意见
